/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FloatImage {
        /**
          * 图片的替代文本
         */
        "alt": string;
        /**
          * 图片的高度
         */
        "height": string;
        /**
          * 图片的URL地址
         */
        "src": string;
        /**
          * 图片的宽度
         */
        "width": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface FloatImageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFloatImageElement;
}
declare global {
    interface HTMLFloatImageElementEventMap {
        "floatImageClick": void;
    }
    interface HTMLFloatImageElement extends Components.FloatImage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFloatImageElementEventMap>(type: K, listener: (this: HTMLFloatImageElement, ev: FloatImageCustomEvent<HTMLFloatImageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFloatImageElementEventMap>(type: K, listener: (this: HTMLFloatImageElement, ev: FloatImageCustomEvent<HTMLFloatImageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFloatImageElement: {
        prototype: HTMLFloatImageElement;
        new (): HTMLFloatImageElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "float-image": HTMLFloatImageElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FloatImage {
        /**
          * 图片的替代文本
         */
        "alt"?: string;
        /**
          * 图片的高度
         */
        "height"?: string;
        /**
          * 点击图片时触发的事件
         */
        "onFloatImageClick"?: (event: FloatImageCustomEvent<void>) => void;
        /**
          * 图片的URL地址
         */
        "src"?: string;
        /**
          * 图片的宽度
         */
        "width"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "float-image": FloatImage;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "float-image": LocalJSX.FloatImage & JSXBase.HTMLAttributes<HTMLFloatImageElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
